### ISSUE TITLE
Dimension out of range (expected to be in range of [-1, 0], but got 1)

### ISSUE THREAD

**Issue by julianoce** [Valentyn1997/xray#1]
Hello, I am having trouble to replicate the training in a custom dataset but with the same transformations in AlphaGAN. In Generator part I get the following error:

`    z = z.view(z.size(0), z.size(1), 1, 1)
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)`

My current parameters for AlphaGAN are:
```
   'AlphaGan': {
        'augmentation': DEFAULT_AUGMENTATION,
        'batch_size': 4,
        'image_resolution': (128, 128),
        'num_epochs': 500,
        'masked_loss_on_val': True,
        'gelr': 0.001,
        'dlr': 0.0001,
        'z_dim': 100,
        'checkpoint_frequency': 2000,
    }
```

Thanks a lot

**Comment by Valentyn1997** [comment]
Hi @julianoce! Sorry for such a long answer time. I cannot reproduce this error - can you please print the shape of input z tensor in Generator's forward method?

**Comment by Valentyn1997** [comment]
Actually, I think, I found the problem. When I run AlphaGan with batch_size = 1 (in your case - the last batch of train DataLoader), I am also getting this error. The problem was with the final squeeze of Encoder's forward() - it should not squeeze batch dimension:
`return mean.squeeze(-1).squeeze(-1), log_var.squeeze(-1).squeeze(-1), p1, p2`

I already pushed changes to master - hope it solves your problem
